// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type CreateUserReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateUserResp struct {
	Id int64 `json:"id"`
}

type GetUserReq struct {
	Id int64 `path:"id"` // 将 form 改为 path
}

type GetUserResp struct {
	User User `json:"user"`
}

type User struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
}
