// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type Blog struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	AuthorId  int64  `json:"author_id"`
	CreatedAt string `json:"created_at"`
}

type CreateBlogReq struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	AuthorId int64  `json:"author_id"`
}

type CreateBlogResp struct {
	Id int64 `json:"id"`
}

type GetBlogReq struct {
	Id int64 `path:"id"` // 将 form 改为 path
}

type GetBlogResp struct {
	Blog Blog `json:"blog"`
}

type ListBlogsReq struct {
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"page_size,optional"`
}

type ListBlogsResp struct {
	Blogs []Blog `json:"blogs"`
	Total int64  `json:"total"`
}
