// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"context"
	"net/http"

	"five/internal/handler/order"
	logicOrder "five/internal/logic/order"  // 添加logic包的导入
	"five/internal/svc"
	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 启动Kafka消费者
	orderLogic := logicOrder.NewOrderLogic(context.Background(), serverCtx)  // 使用logic包
	orderLogic.StartKafkaConsumer()

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/create",
				Handler: order.CreateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/cancel",
				Handler: order.CancelOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/fill",
				Handler: order.FillOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order/get",
				Handler: order.GetOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order/user-orders",
				Handler: order.GetUserOrdersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order/trades",
				Handler: order.GetOrderTradesHandler(serverCtx),
			},
		},
	)
}
