// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	blog "blog/blog/internal/handler/blog"
	"blog/blog/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/blogs",
				Handler: blog.CreateBlogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/blogs",
				Handler: blog.ListBlogsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/blogs/:id",
				Handler: blog.GetBlogHandler(serverCtx),
			},
		},
	)
}
