// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type OrderBookResp struct {
	Bids []OrderItem `json:"bids"`
	Asks []OrderItem `json:"asks"`
}

type OrderCancelReq struct {
	OrderID int64 `json:"order_id"`
	UserID  int64 `json:"user_id"`
}

type OrderCancelResp struct {
	Success bool `json:"success"`
}

type OrderCreateReq struct {
	UserID int64   `json:"user_id"`
	Symbol string  `json:"symbol"` // 交易对
	Price  float64 `json:"price"`  // 价格
	Amount float64 `json:"amount"` // 数量
	Side   int     `json:"side"`   // 买卖方向: 1-买, 2-卖
	Type   int     `json:"type"`   // 订单类型: 1-限价, 2-市价
}

type OrderCreateResp struct {
	OrderID int64 `json:"order_id"`
	Status  int   `json:"status"`
}

type OrderItem struct {
	Price  float64 `json:"price"`
	Amount float64 `json:"amount"`
}

type OrderMatchReq struct {
	TakerOrderID int64   `json:"taker_order_id"`
	MakerOrderID int64   `json:"maker_order_id"`
	Price        float64 `json:"price"`
	Amount       float64 `json:"amount"`
}

type OrderMatchResp struct {
	Success bool    `json:"success"`
	Fee     float64 `json:"fee"` // 手续费
}

type SymbolReq struct {
	Symbol string `json:"symbol"`
}
